title: Our Code Club Flatgame - Mentor Guide
hero_image: images/banner.png
description: Help your creators make an amazing flatgame in Scratch!
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: What your club will make
  - title: Setting up 
    completion:
      - engaged
  - title: Choosing a theme
  - title: Making the artwork
    completion:
      - internal
  - title: Get photos to devices 
  - title: Making the flatgame
    completion:
      - external
